api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'recipes', views.RecipeViewSet)

app_name = 'api'
urlpatterns = [
        # /recipes/
        path('', include(router.urls)),
        #path('', views.RecipeIndexView.as_view(), name = 'recipe_index'),
        # /recipes/4/
        #path('<int:pk>/', views.RecipeDetailView.as_view(), name='recipe_detail'),
        # /recipes/tags/
        #path('tags/', views.TagIndexView.as_view(), name = 'tag_index'),
        # /recipes/tags/1
        #path('tags/<int:pk>', views.TagDetailView.as_view(), name = 'tag_detail'),
]

base/urls.py
from django.contrib import admin
from django.urls import re_path, path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

from . import views


urlpatterns = [
        re_path('^admin/', admin.site.urls),
        path('admin', admin.site.urls),
        re_path(r'^api$', RedirectView.as_view(url = '/api/')),
        path('api/', include('api.urls')),
        path("favicon.ico", views.favicon),
        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
        re_path(r'^.*$', views.HomeView.as_view(), name = 'home'),
        ]

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'
urlpatterns = [
        # /recipes/
        path('', views.RecipeIndexView.as_view(), name = 'recipe_index'),
        # /recipes/4/
        path('<int:pk>/', views.RecipeDetailView.as_view(), name='recipe_detail'),
        # /recipes/tags/
        path('tags/', views.TagIndexView.as_view(), name = 'tag_index'),
        # /recipes/tags/1
        path('tags/<int:pk>', views.TagDetailView.as_view(), name = 'tag_detail'),
]

recipes/models.py
import datetime

from django.db import models
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import get_user_model


class TagField(models.CharField):
    """ Field for tags -- forces all-lowercase """
    def __init__(self, *args, **kwargs):
        super(TagField, self).__init__(*args, **kwargs)

    # def to_python(self, value):
    #     return str(value).lower()
    def __str__(self):
        return self.name


class Tag(models.Model):
    name = TagField(max_length=35, unique=True)
    created_at = models.DateTimeField('Date created', auto_now_add=True)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    """
    Each ingredient can map to many recipes.
    Each recipe can map to many ingredients.
    """
    ## Each ingredient must have a unique name
    name = models.CharField(max_length=400, default="", unique=True)
    def __str__(self):
        return self.name

class ServingUnit(models.Model):
    """
    E.g., "cookie" or "stock" (makes 5 cups stock)
    Each serving unit can map to many recipes.
    Each recipe can map to many serving units.
    """
    ## Each ingredient must have a unique name
    name = models.CharField(max_length=400, default="", unique=True)
    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=400, default="")
    created_at = models.DateTimeField('Date created', auto_now_add=True)
    updated_at = models.DateTimeField('Last updated', auto_now=True)
    description = models.CharField('Description (1 sentence)', max_length=3000, default=None, blank=True, null=True)
    prep_time = models.CharField('Prep time', max_length=3000, default=None, blank=True, null=True)
    cook_time = models.CharField('Cook time', max_length=3000, default=None, blank=True, null=True)
    servings = models.FloatField('Servings', max_length=3000, default=None, blank=True, null=True)
    makes = models.ManyToManyField(ServingUnit, through='RecipeServingUnit')
    introduction = models.CharField("Introduction", max_length = 20000, default=None, blank=True, null=True)
    variations = models.CharField('Variations', max_length = 20000, default=None, blank=True, null=True)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title_image = models.ImageField(default=None, blank=True, null=True, upload_to="title_images")
    directions = models.TextField("Directions", max_length = 20000, default="1. Churn the butter.")
    tags = models.ManyToManyField(Tag, blank=True)

    ## Remove this once section ingredients works:
    ingredients = models.ManyToManyField(Ingredient, through='RecipeIngredient')

    @property
    def has_intro(self):
        return (self.introduction or self.variations)

    @property
    def has_prep(self):
        return (self.prep_time or self.cook_time)

    @property
    def print_updated_at(self):
        return self.updated_at.strftime('%B %d, %Y, %-H:%M %p')

    def print_created_at(self):
        return self.created_at.strftime('%B %d, %Y')

    def __str__(self):
        return self.title

class Section(models.Model):
    """ An ingredients section for a recipe """
    recipe_id = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="sections")
    ingredients = models.ManyToManyField(Ingredient, through='SectionIngredient')
    ## Each section can have any name (not unique)
    name = models.CharField(max_length=400, default="Ingredients", unique=False)
    order = models.FloatField(default=0)
    def __str__(self):
        return self.name

class SectionIngredient(models.Model):
    """ An ingredient, with an amount, used in one recipe """
    section_id = models.ForeignKey(Section, on_delete=models.CASCADE)
    ingredient_id = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    amount = models.FloatField(default=None, null=True, blank=True)
    unit = models.CharField(max_length = 50, null=True, blank=True)
    description = models.CharField(max_length = 400, default=None, null=True, blank=True) # e.g., "freshly squeezed"
    order = models.FloatField(default=0)


class RecipeIngredient(models.Model):
    """ An ingredient, with an amount, used in one recipe """
    recipe_id = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient_id = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    amount = models.FloatField(default=None, null=True, blank=True)
    unit = models.CharField(max_length = 50, null=True, blank=True)
    description = models.CharField(max_length = 400, default=None, null=True, blank=True) # e.g., "freshly squeezed"
    order = models.SmallIntegerField(default=0)

class RecipeServingUnit(models.Model):
    """ A serving unit, with an amount, used in one recipe """
    recipe_id = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    servingunit_id = models.ForeignKey(ServingUnit, on_delete=models.CASCADE)
    amount = models.FloatField(default=None, null=True, blank=True)
    unit = models.CharField(max_length = 50, null=True, blank=True)

recipes/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.utils import timezone
from django import template
from django.core import serializers

from .models import Recipe, Ingredient, RecipeIngredient, Tag, Section, SectionIngredient

# register = template.Library()

class RecipeIndexView(generic.ListView):
    template_name = 'recipes/recipe/index.html'
    queryset = Recipe

    def get_context_data(self, **kwargs):
        context = super(RecipeIndexView, self).get_context_data(**kwargs)

        n_recent_recipes = 20
        latest_recipes_list = Recipe.objects.filter(
                created_at__lte=timezone.now()).order_by('-created_at')[:n_recent_recipes]
        latest_recipe =  Recipe.objects.filter(
                created_at__lte=timezone.now()).order_by('-created_at')[:1]

        all_recipes_list = Recipe.objects.all()
        all_recipes_json = serializers.serialize('json', all_recipes_list)
        context["all_recipes_json"] = all_recipes_json

        # TODO: add "updated" date, like homepage has
        context["latest_recipes_list"] = latest_recipes_list
        context["latest_recipe"] = latest_recipe
        context["n_recent_recipes"] = n_recent_recipes
        context["all_recipes_list"] = all_recipes_list

        return context



class TagIndexView(generic.ListView):
    template_name = 'recipes/tag/index.html'
    queryset = Recipe, Tag

    def get_context_data(self, **kwargs):
        context = super(TagIndexView, self).get_context_data(**kwargs)

        n_recent_tags = 20
        latest_tags_list = Tag.objects.filter(
                created_at__lte=timezone.now()).order_by('-created_at')[:n_recent_tags]
        latest_tag =  Tag.objects.filter(
                created_at__lte=timezone.now()).order_by('-created_at')[:1]
        all_tags_list = Tag.objects.all()


        all_recipes_list = Recipe.objects.all()
        all_recipes_json = serializers.serialize('json', all_recipes_list)
        context["all_recipes_json"] = all_recipes_json

        # TODO: add "updated" date, like homepage has
        context["latest_tags_list"] = latest_tags_list
        context["latest_tag"] = latest_tag
        context["n_recent_tags"] = n_recent_tags
        context["all_tags_list"] = all_tags_list

        return context

class RecipeDetailView(generic.DetailView):
    template_name = 'recipes/recipe/detail.html'
    model = Recipe

    def get_context_data(self, **kwargs):
        context = super(RecipeDetailView, self).get_context_data(**kwargs)

        has_title_image = self.object.title_image is not None
        has_description = self.object.description is not None
        has_intro = self.object.introduction is not None or self.object.variations is not None
        has_prep = self.object.prep_time is not None or self.object.cook_time is not None
        has_servings = self.object.servings is not None
        has_makes = self.object.makes.exists()
        has_ingredients = self.object.ingredients.exists()
        has_directions = self.object.directions is not None
        has_tags = self.object.tags is not None

        ## has_ingredients: there is at least one section with at least one ingredient.
        ## section_ingredients returns an object with length = number of ingredients (in all sections?)
        # section_ingredients = Section.objects.filter(recipe_id=self.object, sectioningredient__isnull=False)
        # has_ingredients = section_ingredients.exists()

        ## has_multiple sections: the recipe has more than one section
        # has_multiple_sections = (self.object.sections.count() > 1)
        ## For now (until I fix sections)
        has_multiple_sections = 0 # Hack

        ## Author label is full name, if available, or else user id.
        # author_fullname = self.object.author.get_full_name()
        # author_label = author_fullname if author_fullname else self.object.author
        author_label = self.object.author.get_full_name() or self.object.author

        context["has_prep"] = has_prep
        context["has_description"] = has_description
        context["has_intro"] = has_intro
        context["has_servings"] = has_servings
        context["has_makes"] = has_makes
        context["has_ingredients"] = has_ingredients
        context["has_directions"] = has_directions
        context["has_multiple_sections"] = has_multiple_sections
        context["has_tags"] = has_tags
        context["author_label"] = author_label


        ## For testing:
        context["section_count"] = self.object.sections.count()
        section_test = self.object.sections.all()
        context["section_test"] = section_test



        all_recipes_list = Recipe.objects.all()
        all_recipes_json = serializers.serialize('json', all_recipes_list)
        context["all_recipes_json"] = all_recipes_json

        return context

class TagDetailView(generic.DetailView):
    template_name = 'recipes/tag/detail.html'
    model = Tag

    def get_context_data(self, **kwargs):
        context = super(TagDetailView, self).get_context_data(**kwargs)
        # Object is accessible through self.object or self.get_object()
        recipes_list = Recipe.objects.filter(tags=(self.object))
        # Then return
        context["recipes"] = recipes_list


        all_recipes_list = Recipe.objects.all()
        all_recipes_json = serializers.serialize('json', all_recipes_list)
        context["all_recipes_json"] = all_recipes_json

        return context

templates/recipes/recipe/detail.html
{% load static %}
{% load humanizelib %}
{% load tz %}

{% load recipes_customtags %}

<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ recipe.title|capfirst|truncatechars:40 }} | {{ SITE_TITLE_SHORT }}</title>
    {% include "base/partials/base_style.html" %}
    <link rel="stylesheet" href="{% static 'recipes/recipe_detail.css' %}">
  </head>


  <body>

    <div class="content-grid">
      <div class="content-grid__header">
          {% include "base/partials/navbar_minimal.html" %}
      </div>

      <div class="content-grid__main--recipe">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <div class="title-image-grid">
          <div class="title-image_grid__text">
            <div class="recipe-title">
              <h1>{{ recipe.title }}</h1>
            </div>

            {# is there is no intro, put title image in grid with just tite #}
            {#TODO: handle every combination of intro & prep. #}
            {% if not has_intro %}
              {% with has_intro=False has_prep=recipe.has_prep %}
                {% include "../partials/recipe_image.html" %}
              {% endwith %}
            {% endif %}

            {#TODO: Make flexbox for description, intro, variations, prep time #}
            {% if has_intro %}
              <div class="introduction-variations">
                {# {% if has_description %} #}
                  {#   {{ recipe.description }}. #}
                {# {% endif %} #}
                {% if recipe.introduction is not None %}
                  <p> {{ recipe.introduction }} </p>
                {% endif %}
                {% if recipe.variations is not None %}
                  <p> <i>Variations.</i> {{  recipe.variations }} </p>
                {% endif %}
              </div>
            {% endif %}
          </div>

          {# This (?) exists outside the title image grid IFF a recipe intro is present. #}
          {% if  has_intro %}
            {% include "../partials/recipe_image.html" with has_intro=True %}
          {% endif %}

        </div>

        {% if has_prep %}
          <div class="prep-cook-time">
            {% if recipe.prep_time is not None %}
              Prep time: {{ recipe.prep_time }}
            {% endif %}
            {% if recipe.prep_time is not None and recipe.cook_time is not None %}
              |
            {% endif %}
            {% if recipe.cook_time is not None %}
              Cook time: {{  recipe.cook_time }}
            {% endif %}
          </div>
        {% endif %}


        {% if has_ingredients or has_directions %}

          <div class="ingredients-directions-container">
            {% if has_ingredients %}
              <div class="ingredients">
                <h3 class="ingredients-directions-header"> Ingredients </h3>
                {% if has_servings %}
                  <p class = "servings">
                  <i>Serves {{  recipe.servings|fractional }}</i>
                  </p>
                {% endif %}
                {% if has_makes %}
                  <p class = "makes">
                  {% if recipe.recipeservingunit_set.all is not None %}
                    {% for rsu in recipe.recipeservingunit_set.all %}
                      <i>Makes
                        {% with item=rsu item_type="serving_unit" %}
                          {% include "../partials/item_with_amount.html" %}
                        {% endwith %}
                      </i>
                    {% endfor %}
                  {% endif %}
                  </p>
                {% endif %}


                {# loop through recipe ingredients #}
                <ul class="ingredients-list">
                  {% if recipe.recipeingredient_set.all is not None %}
                    {% for ri in recipe.recipeingredient_set.all|sort_by:"order" %}
                      <li>
                        {% with item=ri item_type="section_ingredient" %}
                          {% include "../partials/item_with_amount.html" %}
                        {% endwith %}
                      </li>
                    {% endfor %}
                  {% endif %}
                </ul>
              </div>

              {# TODO: implement recipe sections #}
              {# TODO: pass in sorted list of sections, defined in views. #}

              {# {% for section in recipe.sections.all|sort_by:'order' %} #}
                {#   {% if has_multiple_sections %} #}
                  {#     <h4 class="ingredients-section-header">{{ section.name }}</h4> #}
                  {#     {{ section.ingredients_set.all }} #}
                {#   {% endif %} #}
                {#   {% with section_ingredients=section.sectioningredient_set.all %} #}
                  {#     {% include "../partials/section_ingredients_list.html" %} #}
                {#   {% endwith %} #}
              {# {% endfor %} #}

              {# </div> #}

          {% endif %}
          {% if has_ingredients and has_directions %}
            <div class="ingredients-directions-separator">
            </div>
          {%endif %}
          {% if has_directions %}
            <div class="directions">
              <h3 class="ingredients-directions-header"> Directions </h3>
              {{ recipe.directions|linebreaks }}
            </div>
          {% endif %}
      </div>

    {% endif %}

    {% if has_tags %}
      <div class="tags">
        {% for tag in recipe.tags.all %}
          <a href="{% url 'recipes:tag_detail' tag.id %}">{{ tag.name }}</a>
          {% if not forloop.last %}|{% endif %}
        {% endfor %}
      </div>
    {% endif %}
    </div>

      <div class="content-grid__footer">
        <div class="content-grid__footer__note">
          <p>
          <em>
          {# Show date last updated, if different from date created #}
          {% timezone "US/Eastern" %}
          {% if recipe.created_at|date == recipe.updated_at|date %}
            Added by {{ author_label }} {{ recipe.created_at.date }}
          {% else %}
            Added by {{ author_label }} {{ recipe.created_at|date:"F j, o" }}
            | Updated {{ recipe.updated_at|date:"F j, o" }} {{ recipe.updated_at|time:"P" }}
          {% endif %}
          {% endtimezone %}
          </em>
          </p>
        </div>
        <div class="content-grid__footer__navbuttons">
          {% include "base/partials/navbar_footer.html" %}
        </div>
      </div>

    </div>

  </body>

</html>

templates/recipes/recipe/index.html
{% load static %}
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Recipes | {{ SITE_TITLE_SHORT }}</title>
    <link rel="stylesheet" href="{% static 'base/style.css' %}">

    {% include "base/partials/base_style.html" %}
    {% include "base/partials/frontend.html" %}

  </head>

  <body>

    <div class="content-grid">

      <div class="content-grid__header">
        {% include "base/partials/navbar.html" %}
      </div>

      <div class="content-grid__main">
        <div class="index-block">
          <div class="index-block__header">
            All Recipes
            <hr/>
          </div>
          {% if all_recipes_list %}
            <ul class="index-block__content">
              {% for recipe in all_recipes_list|dictsort:"title" %}
                <li>
                  {% include "base/partials/recipe_index_list_entry.html" %}
                </li>
              {% endfor %}
            </ul>
          {% else %}
            <p>No recipes are available.</p>
          {% endif %}
        </div>
      </div>

      <div class="content-grid__footer">
        <div class="content-grid__footer__navbuttons">
          {% include "base/partials/navbar_footer.html" %}
        </div>
      </div>

    </div>

  </body>

</html>