api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'recipes', views.RecipeViewSet)

app_name = 'api'
urlpatterns = [
        # /recipes/
        path('', include(router.urls)),
        #path('', views.RecipeIndexView.as_view(), name = 'recipe_index'),
        # /recipes/4/
        #path('<int:pk>/', views.RecipeDetailView.as_view(), name='recipe_detail'),
        # /recipes/tags/
        #path('tags/', views.TagIndexView.as_view(), name = 'tag_index'),
        # /recipes/tags/1
        #path('tags/<int:pk>', views.TagDetailView.as_view(), name = 'tag_detail'),
]

base/urls.py
from django.contrib import admin
from django.urls import re_path, path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

from . import views


urlpatterns = [
        re_path('^admin/', admin.site.urls),
        path('admin', admin.site.urls),
        re_path(r'^api$', RedirectView.as_view(url = '/api/')),
        path('api/', include('api.urls')),
        path("favicon.ico", views.favicon),
        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
        re_path(r'^.*$', views.HomeView.as_view(), name = 'home'),
        ]

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'
urlpatterns = [
        # /recipes/
        path('', views.RecipeIndexView.as_view(), name = 'recipe_index'),
        # /recipes/4/
        path('<int:pk>/', views.RecipeDetailView.as_view(), name='recipe_detail'),
        # /recipes/tags/
        path('tags/', views.TagIndexView.as_view(), name = 'tag_index'),
        # /recipes/tags/1
        path('tags/<int:pk>', views.TagDetailView.as_view(), name = 'tag_detail'),
]

base/views.py
# from django.shortcuts import render
from django.views import generic
from django.utils import timezone
from django.conf import settings
from django.http import FileResponse, HttpRequest, HttpResponse
from django.views.decorators.cache import cache_control
from django.views.decorators.http import require_GET
from django.core import serializers

from recipes.models import Recipe, Tag

import json

## Set up favicon
## https://adamj.eu/tech/2022/01/18/how-to-add-a-favicon-to-your-django-site/
## https://perma.cc/338Z-Z84G
@require_GET
@cache_control(max_age=60 * 60 * 24, immutable=True, public=True)  # one day
def favicon(request: HttpRequest) -> HttpResponse:
    file = (settings.BASE_DIR / "static" / "favicon.ico").open("rb")
    return FileResponse(file)

class HomeView(generic.ListView):
    template_name = 'base/home.html'
    queryset = Recipe

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)

        all_recipes_list = Recipe.objects.all()
        all_recipes_json = serializers.serialize('json', all_recipes_list)

        n_recent_recipes = 20
        n_recent_tags = 20
        n_all_recipes = Recipe.objects.all().count()
        n_all_tags = Tag.objects.all().count()
        latest_recipes_list = Recipe.objects.filter(
                created_at__lte=timezone.now()).order_by('-created_at')[:n_recent_recipes]
        latest_tags_list = Tag.objects.filter(
                created_at__lte=timezone.now()).order_by('-created_at')[:n_recent_tags]
        latest_recipe =  Recipe.objects.filter(
                created_at__lte=timezone.now()).order_by('-created_at')[:1]


        context["all_recipes_list"] = all_recipes_list
        context["all_recipes_json"] = all_recipes_json

        context["latest_recipes_list"] = latest_recipes_list
        context["latest_tags_list"] = latest_tags_list
        context["latest_recipe"] = latest_recipe
        context["n_recent_recipes"] = n_recent_recipes
        context["n_recent_tags"] = n_recent_tags
        context["n_all_recipes"] = n_all_recipes
        context["n_all_tags"] = n_all_tags

        return context

base/templates/base/home.html
{% load static %}

<link rel="stylesheet" href="{% static 'base/style.css' %}">

<title>{{ SITE_TITLE }}: A simple site for family recipes | Home</title>

<body>

  <div class="index-grid">
    <div class="index-grid__body">
      <div class="index-header">
        <div class="header-link">
          <a href="{% url 'recipes:recipe_index' %}">New Recipes</a>
        </div>
      </div>

      {% if latest_recipes_list %}
        <ul class="index-list">
          {% for recipe in latest_recipes_list %}
            <li>
              <a href="{% url 'recipes:recipe_detail' recipe.id %}">{{ recipe.title }}</a>
              {% if recipe.description %}
                <em>&nbsp;—&nbsp;&nbsp;{{ recipe.description|capfirst }}</em>
              {% endif %}
            </li>
          {% endfor %}
          {% if n_all_recipes >= n_recent_recipes %}
            <li>
              <div class="see-all-link">
                <a href="{% url 'recipes:recipe_index' %}">
                  <em>—See all {{ n_all_recipes }} recipes—</em>
                </a>
              </div>
            </li>
          {% endif %}
        </ul>
      {% else %}
        <p>No recipes are available.</p>
      {% endif %}

      <div class="index-header">
        <div class="header-link">
          <a href="{% url 'recipes:tag_index' %}">New Categories</a>
        </div>
      </div>

      {% if latest_tags_list %}
        <ul class="index-list">
          {% for tag in latest_tags_list %}
            <li><a href="{% url 'recipes:tag_detail' tag.id %}">{{ tag.name|capfirst }}</a></li>
          {% endfor %}
          {% if n_all_tags > n_recent_tags %}
            <li>
              <div class="see-all-link">
                <a href="{% url 'recipes:tag_index' %}">
                  <em>—See all {{ n_all_tags }} categories—</em>
                </a>
              </div>
            </li>
          {% endif %}
        </ul>
      {% else %}
        <p>No category tags are available.</p>
      {% endif %}
    </div>

    <div class="index-grid__footer">
      <p>
      <em>
        {% for recipe in latest_recipe %}
          Updated {{ recipe.updated_at|date:"F j, o" }}
        {% endfor %}

      </em>
      <br>
      <a href="/">Home</a> {# TODO: change to "about", add "about" page. #}
      | <a href="{% url 'recipes:recipe_index' %}">Recipes</a>
      | <a href="{% url 'recipes:tag_index' %}">Categories</a>
      </p>
    </div>

  </div>

</body>